config/routes.rb
Rails.application.routes.draw do
devise_for :users

 root 'users#welcome'

  resources :requests

  resources :users

  resources :passes

  resources :events

  resources :clubs

end

app/controllers/passes_controller.rb
class PassesController < ApplicationController
  before_action :set_pass, only: [:show, :edit, :update, :destroy]

  # GET /passes
  # GET /passes.json
  def index
    @passes = current_user.passes
  end

  # GET /passes/1
  # GET /passes/1.json
  def show
  end

  # GET /passes/new
  def new
    @pass = Pass.new
  end

  # GET /passes/1/edit
  def edit
  end

  # POST /passes
  # POST /passes.json
  def create
    @pass = Pass.new(pass_params)

    respond_to do |format|
      if @pass.save
        format.html { redirect_to user_url current_user.id, notice: 'Pass was successfully created.' }
        format.json { render :show, status: :created, location: @pass }
      else
        format.html { render :new }
        format.json { render json: @pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /passes/1
  # PATCH/PUT /passes/1.json
  def update
    respond_to do |format|
      if @pass.update(pass_params)
        format.html { redirect_to @pass, notice: 'Pass was successfully updated.' }
        format.json { render :show, status: :ok, location: @pass }
      else
        format.html { render :edit }
        format.json { render json: @pass.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /passes/1
  # DELETE /passes/1.json
  def destroy
    @pass.destroy
    respond_to do |format|
      format.html { redirect_to passes_url, notice: 'Pass was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pass
      @pass = Pass.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pass_params
      params.require(:pass).permit(:event_id, :user_id, :quantity)
    end
end

app/helpers/passes_helper.rb
module PassesHelper
end

app/views/passes/_form.html.erb
<%= form_for(@pass) do |f| %>
  <% if @pass.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pass.errors.count, "error") %> prohibited this pass from being saved:</h2>

      <ul>
      <% @pass.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.hidden_field :event_id, :value=>params[:event_id] %>
  </div>
  <div class="field">
    <%= f.hidden_field :user_id, :value=>current_user.id %>
  </div>
  <div class="field">
    <%= f.label :quantity %><br>
    <%= f.number_field :quantity %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-default" %>
  </div>
<% end %>

app/views/passes/edit.html.erb
<h1>Editing pass</h1>

<%= render 'form' %>

<%= link_to 'Show', @pass %> |
<%= link_to 'Back', passes_path %>

app/views/passes/index.html.erb
<h1>Listing passes</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Event</th>
      <th>Quantity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @passes.each do |pass| %>
      <tr>
        <td><%= pass.event.details %></td>
        <td><%= pass.quantity %></td>
        <td><%= link_to 'Show', pass %></td>
        <td><%= link_to 'Edit', edit_pass_path(pass) %></td>
        <td><%= link_to 'Destroy', pass, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/passes/new.html.erb
<h1>New pass</h1>

<%= render 'form' %>

<%= link_to 'Back', passes_path %>

app/views/passes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Event:</strong>
  <%= @pass.event_id %>
</p>

<p>
  <strong>User:</strong>
  <%= @pass.user_id %>
</p>

<p>
  <strong>Quantity:</strong>
  <%= @pass.quantity %>
</p>

<%= link_to 'Edit', edit_pass_path(@pass) %> |
<%= link_to 'Back', passes_path %>