config/routes.rb
Rails.application.routes.draw do
devise_for :users

 root 'users#welcome'

  resources :requests

  resources :users

  resources :passes

  resources :events

  resources :clubs

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
validates :name, presence: true

def club
  if self.club_id.present?
    return Club.find(self.club_id).name
  else
    return "No Club"
  end
end
def passes
  Pass.where(:user_id=>self.id)
end
def requests
  Request.where(:user_id=>self.id)
end
def events_held
  Event.where(:id=>passes.pluck(:event_id))
end
def events_requested
  Event.where(:id=>requests.pluck(:event_id))
end
def users_who_have_what_you_want
    this_persons_requested_event_ids= requests.pluck(:event_id)
    passes_that_are_available_with_requests_ids=Pass.where(:event_id=>this_persons_requested_event_ids)
    user_ids_passholders=passes_that_are_available_with_requests_ids.pluck(:user_id)
    User.where(:id=>user_ids_passholders)
  end
  def users_who_want_what_you_have
    requests_for_your_passes=Request.where(:event_id=>passes.pluck(:event_id))
    user_requester_ids=requests_for_your_passes.pluck(:user_id)
    User.where(:id=>user_requester_ids)
  end
  def matches
    array_of_matches=Array.new
    users_who_have_what_you_want.each do |user_who_has_what_you_want|
      if users_who_want_what_you_have.include?(user_who_has_what_you_want)
        array_of_matches=array_of_matches.push(user_who_has_what_you_want)
      end
    end
    return array_of_matches
  end
  def matching_passes
    users_events_requested=events_requested
    array_of_matching_passes=Array.new
    matches.each do |match|
      match.passes.each do |pass|
        if events_requested.pluck(:id).include?(pass.event_id)
          array_of_matching_passes.push(pass)
        end
      end
    end
    return array_of_matching_passes
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:club_id, :name, :officer?)
    end
    def welcome
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_event_table.html.erb
<h1>Event Table</h1>
<table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Club</th>
      <th>Theme</th>
      <th>Info</th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% Event.all.each do |event| %>
      <tr>
        <td><%= event.date %></td>
        <td><%= event.club.name %></td>
        <td><%= event.theme %></td>
        <td><%= event.info %></td>


        <td>
          <%if current_user.events_requested.include?(event)==false%>
          <%=form_tag new_request_url, :method=>"get" %>
            <%=hidden_field_tag "event_id", event.id%>
            <%=submit_tag "I want a pass for this", :class=>"btn btn-warning"%>
          </form>
          <%else%>
          <button class="btn btn-warning active">Requested!</button>

          <%end%>

        </td>



        <td>
        <%if current_user.events_held.include?(event)==false%>
         <%=form_tag new_pass_path, :method=>"get" %>
            <%=hidden_field_tag "event_id", event.id%>
           <%=submit_tag "I have a pass for this", :class=>"btn btn-success"%>
          </form>
            <%else%>
            <button class="btn btn-success active">Got it!</button>

          <% end %>

          </td>

      </tr>


    <% end %>
  </tbody>
</table>

app/views/users/_matching_table.html.erb
 <h1>Here are your matches</h1>
    <table class="table table-hover">
      <tr>
        <th>Contact</th>
        <th>What they have that you want</th>
        <th>What you have that they want</th>

      <% current_user.matching_passes.each do |matching_pass| %>
      <tr>
        <td><%=matching_pass.owner.email%></td>
        <td><%=matching_pass.event.details%></td>
        <td><%matching_pass.events_they_want(current_user).each do |event|%>
              <%=event.details%><br>
              <%end%>
        </td>
       <tr>
      <% end %>

    </table>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>
Welcome, <%=current_user.name%>
</p>
<%=render 'matching_table'%>
<%if current_user.officer?%>
<%=link_to "Add an Event for your club", new_event_url%>
<%end%>
<%=render 'event_table'%>

app/views/users/welcome.html.erb
<h1 class="splash-center"><i style="font-size:600%" class="fa fa-tags"></i></h2>
<h1 class="splash-center">Princeton Pass Exchange</h1>