config/routes.rb
Rails.application.routes.draw do
devise_for :users

 root 'users#welcome'

  resources :requests

  resources :users

  resources :passes

  resources :events

  resources :clubs

end

app/models/event.rb
class Event < ActiveRecord::Base
validates :date, presence: true
validates :club_id, presence: true

def club
  Club.find(self.club_id)
end
def passes
  Pass.where(:event_id=>self.id)
end
def requests
  Request.where(:event_id=>self.id)
end

def users_with_passes
  User.where(:id=>self.passes.pluck(:user_id))
end
def users_with_requests
  User.where(:id=>self.requests.pluck(:user_id))
end
def details
  return "#{club.name} on #{date}"
end
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_action :set_event, only: [:show, :edit, :update, :destroy]

  # GET /events
  # GET /events.json
  def index
    @events = Event.where(:club_id=>current_user.club_id)
  end

  # GET /events/1
  # GET /events/1.json
  def show
  end

  # GET /events/new
  def new
    @event = Event.new
  end

  # GET /events/1/edit
  def edit
  end

  # POST /events
  # POST /events.json
  def create
    @event = Event.new(event_params)

    respond_to do |format|
      if @event.save
        format.html { redirect_to user_url current_user.id, notice: 'Event was successfully created.' }
        format.json { render :show, status: :created, location: @event }
      else
        format.html { render :new }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /events/1
  # PATCH/PUT /events/1.json
  def update
    respond_to do |format|
      if @event.update(event_params)
        format.html { redirect_to @event, notice: 'Event was successfully updated.' }
        format.json { render :show, status: :ok, location: @event }
      else
        format.html { render :edit }
        format.json { render json: @event.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /events/1
  # DELETE /events/1.json
  def destroy
    @event.destroy
    respond_to do |format|
      format.html { redirect_to events_url, notice: 'Event was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_event
      @event = Event.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def event_params
      params.require(:event).permit(:date, :club_id, :theme, :info)
    end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/_form.html.erb
<%= form_for(@event) do |f| %>
  <% if @event.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@event.errors.count, "error") %> prohibited this event from being saved:</h2>

      <ul>
      <% @event.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :date %><br>
    <%= f.date_select :date %>
  </div>
  <div class="field">
       <%= f.hidden_field :club_id, :value=>current_user.club_id %>

  </div>
  <div class="field">
    <%= f.label :theme %><br>
    <%= f.text_field :theme %>
  </div>
  <div class="field">
    <%= f.label :info %><br>
    <%= f.text_field :info %>
  </div>
  <div class="actions">
    <%= f.submit :class=>"btn btn-default" %>
  </div>
<% end %>

app/views/events/edit.html.erb
<h1>Editing event</h1>

<%= render 'form' %>

<%= link_to 'Show', @event %> |
<%= link_to 'Back', events_path %>

app/views/events/index.html.erb
<h1>Listing events</h1>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Date</th>
      <th>Club</th>
      <th>Theme</th>
      <th>Info</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @events.each do |event| %>
      <tr>
        <td><%= event.date %></td>
        <td><%= event.club_id %></td>
        <td><%= event.theme %></td>
        <td><%= event.info %></td>
        <td><%= link_to 'Show', event %></td>
        <td><%= link_to 'Edit', edit_event_path(event) %></td>
        <td><%= link_to 'Destroy', event, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/events/new.html.erb
<h1>New event</h1>

<%= render 'form' %>

<%= link_to 'Back', events_path %>

app/views/events/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Date:</strong>
  <%= @event.date %>
</p>

<p>
  <strong>Club:</strong>
  <%= @event.club_id %>
</p>

<p>
  <strong>Theme:</strong>
  <%= @event.theme %>
</p>

<p>
  <strong>Info:</strong>
  <%= @event.info %>
</p>

<%= link_to 'Edit', edit_event_path(@event) %> |
<%= link_to 'Back', events_path %>